# Generated by Django 2.2.4 on 2021-10-19 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0003_auto_20211016_0442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
